import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AuthProvider from "../contexts/AuthProvider";
import { LoadingProvider } from "@/contexts/LoadingProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <LoadingProvider>
        <body className={inter.className}>{children}</body>
      </LoadingProvider>
      </AuthProvider>
    </html>
  );
}
